AWSTemplateFormatVersion: "2010-09-09"
Description: "API Gateway with Cognito authentication, Lambda functions, and caching"

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Infrastructure Configuration"
        Parameters:
          - LambdaFunctionsS3Bucket
      - Label:
          default: "API Configuration"
        Parameters:
          - AlphaVantageApiKey
    ParameterLabels:
      LambdaFunctionsS3Bucket:
        default: "S3 Bucket Name"
      AlphaVantageApiKey:
        default: "Alpha Vantage API Key"

Parameters:
  LambdaFunctionsS3Bucket:
    Type: String
    Description: "S3 Bucket containing lambda functions"
    Default: scansource-lambda-bucket
    AllowedPattern: "^[a-z0-9][a-z0-9-]*[a-z0-9]$"
    ConstraintDescription: "Bucket name must be lowercase alphanumeric with hyphens"
    MinLength: 3
    MaxLength: 63

  AlphaVantageApiKey:
    Type: String
    Description: "Alpha Vantage API Key (16 alphanumeric characters)"
    NoEcho: true
    AllowedPattern: "^[A-Z0-9]{16}$"
    ConstraintDescription: "Must be exactly 16 uppercase alphanumeric characters"
    MinLength: 16
    MaxLength: 16

Resources:
  #IAM Roles + Account
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: SecretsManagerAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: secretsmanager:GetSecretValue
                Resource: !Ref ApiKeySecret

  ApiGatewayCloudWatchRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs

  ApiGatewayAccount:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt ApiGatewayCloudWatchRole.Arn

  #Cognito + Authorizer
  UserPool:
    Type: AWS::Cognito::UserPool
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      UserPoolName: !Sub "${AWS::StackName}-UserPool"
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
          Mutable: false
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      UserPoolTags:
        Project: APIGatewayAssessment
        ManagedBy: CloudFormation
        Stack: !Ref AWS::StackName

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: ScansourceAppClient
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      PreventUserExistenceErrors: ENABLED

  ApiAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      Name: CognitoAuthorizer
      Type: COGNITO_USER_POOLS
      IdentitySource: method.request.header.Authorization
      RestApiId: !Ref ScansourceAPI
      ProviderARNs:
        - !GetAtt UserPool.Arn

  #Lambda functions
  Lambda1:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-NodeFunction"
      Runtime: nodejs24.x
      Handler: index.handler
      Role: !GetAtt LambdaRole.Arn
      Timeout: 20
      MemorySize: 256
      Environment:
        Variables:
          SECRET_ARN: !Ref ApiKeySecret
      Code:
        S3Bucket: !Ref LambdaFunctionsS3Bucket
        S3Key: lambda1.zip
      Tags:
        - Key: Project
          Value: APIGatewayAssessment
        - Key: ManagedBy
          Value: CloudFormation
        - Key: Stack
          Value: !Ref AWS::StackName

  Lambda2:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-PythonFunction"
      Runtime: python3.12
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaRole.Arn
      Timeout: 20
      MemorySize: 256
      Code:
        S3Bucket: !Ref LambdaFunctionsS3Bucket
        S3Key: lambda2.zip
      Tags:
        - Key: Project
          Value: APIGatewayAssessment
        - Key: ManagedBy
          Value: CloudFormation
        - Key: Stack
          Value: !Ref AWS::StackName

  #API Gateway
  ScansourceAPI:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub "${AWS::StackName}-API"
      Description: "API Gateway for lambda functions using REST API (PROXY)"
      EndpointConfiguration:
        Types:
          - REGIONAL
      Tags:
        - Key: Project
          Value: APIGatewayAssessment
        - Key: ManagedBy
          Value: CloudFormation
        - Key: Stack
          Value: !Ref AWS::StackName

  ApiPathRoot:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ScansourceAPI
      ParentId: !GetAtt ScansourceAPI.RootResourceId
      PathPart: api

  ApiPathV1:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ScansourceAPI
      ParentId: !Ref ApiPathRoot
      PathPart: v1

  ApiPathNode:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ScansourceAPI
      ParentId: !Ref ApiPathV1
      PathPart: stocks

  EndpointGetNode:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ScansourceAPI
      ResourceId: !Ref ApiPathNode
      HttpMethod: GET
      AuthorizationType: COGNITO_USER_POOLS
      AuthorizerId: !Ref ApiAuthorizer
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Lambda1.Arn}/invocations

  ExecuteGetNode:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref Lambda1
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ScansourceAPI}/*/GET/api/v1/stocks

  ApiPathPython:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ScansourceAPI
      ParentId: !Ref ApiPathV1
      PathPart: weather

  EndpointGetPython:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ScansourceAPI
      ResourceId: !Ref ApiPathPython
      HttpMethod: GET
      AuthorizationType: COGNITO_USER_POOLS
      AuthorizerId: !Ref ApiAuthorizer
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Lambda2.Arn}/invocations

  ExecuteGetPython:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref Lambda2
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ScansourceAPI}/*/GET/api/v1/weather

  #Deployment
  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - EndpointGetNode
      - EndpointGetPython
      - ApiAuthorizer
    Properties:
      RestApiId: !Ref ScansourceAPI
      Description: "API Gateway Deployment with Cognito"

  #Stage
  ApiStage:
    Type: AWS::ApiGateway::Stage
    DependsOn: ApiGatewayAccount
    Properties:
      RestApiId: !Ref ScansourceAPI
      DeploymentId: !Ref ApiDeployment
      StageName: prod
      Description: "Production Stage for API Gateway"
      CacheClusterEnabled: true
      CacheClusterSize: "0.5"
      MethodSettings:
        - ResourcePath: /api/v1/stocks
          HttpMethod: GET
          CachingEnabled: true
          CacheTtlInSeconds: 300
          CacheDataEncrypted: true
          LoggingLevel: INFO
          DataTraceEnabled: true
          MetricsEnabled: true
        - ResourcePath: /api/v1/weather
          HttpMethod: GET
          CachingEnabled: true
          CacheTtlInSeconds: 300
          CacheDataEncrypted: true
          LoggingLevel: INFO
          DataTraceEnabled: true
          MetricsEnabled: true

  #AWS Secrets Manager + Secrets
  ApiKeySecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: !Sub "${AWS::StackName}-alphavantage-api-key"
      SecretString: !Sub '{"apiKey": "${AlphaVantageApiKey}"}'

  #CloudWatch Alarms
  Lambda1ErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${AWS::StackName}-Lambda1-Errors"
      AlarmDescription: "Alert when NodeFunction has errors"
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref Lambda1
      TreatMissingData: notBreaching

  Lambda2ErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${AWS::StackName}-Lambda2-Errors"
      AlarmDescription: "Alert when PythonFunction has errors"
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref Lambda2
      TreatMissingData: notBreaching

  ApiGateway5XXAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${AWS::StackName}-API-5XX-Errors"
      AlarmDescription: "Alert on API Gateway server errors"
      MetricName: 5XXError
      Namespace: AWS/ApiGateway
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 2
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ApiName
          Value: !Ref ScansourceAPI
        - Name: Stage
          Value: prod
      TreatMissingData: notBreaching

Outputs:
  ApiEndpointUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ScansourceAPI}.execute-api.${AWS::Region}.amazonaws.com/prod"

  StocksEndpoint:
    Description: "Stocks function endpoint"
    Value: !Sub "https://${ScansourceAPI}.execute-api.${AWS::Region}.amazonaws.com/prod/api/v1/stocks"

  WeatherEndpoint:
    Description: "Weather function endpoint"
    Value: !Sub "https://${ScansourceAPI}.execute-api.${AWS::Region}.amazonaws.com/prod/api/v1/weather"

  UserPoolId:
    Description: "Cognito User Pool ID"
    Value: !Ref UserPool

  UserPoolClientId:
    Description: "Cognito User Pool Client ID"
    Value: !Ref UserPoolClient

  UserPoolArn:
    Description: "Cognito User Pool ARN"
    Value: !GetAtt UserPool.Arn

  Region:
    Description: "AWS Region"
    Value: !Ref AWS::Region

  StackName:
    Description: "CloudFormation Stack Name"
    Value: !Ref AWS::StackName

  ApiGatewayId:
    Description: "API Gateway ID"
    Value: !Ref ScansourceAPI

  SecretArn:
    Description: "Secrets Manager ARN for API key"
    Value: !Ref ApiKeySecret

  Lambda1LogGroup:
    Description: "CloudWatch Log Group for NodeFunction"
    Value: "/aws/lambda/NodeFunction"

  Lambda2LogGroup:
    Description: "CloudWatch Log Group for PythonFunction"
    Value: "/aws/lambda/PythonFunction"

  ApiGatewayLogGroup:
    Description: "CloudWatch Log Group for API Gateway"
    Value: !Sub "API-Gateway-Execution-Logs_${ScansourceAPI}/prod"
